### PR TITLE
Update readme: pull requests are welcome

### PR DESCRIPTION
**Pull request by NIKHIL-techgeek**
With this PR , We are inviting everybody to contribute to the project.
I have updated the readme file to inform that PRs are open

### CODE REVIEW

**Comment by arun-esh** [comment]
@jalpa015 Here we got new PR. 
I had discussion with @NIKHIL-techgeek today and we are thinking to display that we are accepting the PRs. 

Please provide your thoughts.

**Comment by arun-esh** [comment]
Need a better way to display the information. Should we remove the "horizontal line" between the texts...??
image

**Comment by jalpa015** [comment]
@arun-esh Are we still showcasing this project as COMP 3340 Project? Maybe we can make edits to that?

**Comment by arun-esh** [comment]
> @arun-esh Are we still showcasing this project as COMP 3340 Project? Maybe we can make edits to that?

I didn't even thought about it. 
Suggest repo names: 
@NIKHIL-techgeek @jalpa015 @HarshitOO7 @TanveerPoonia

**Comment by arun-esh** [comment]
I will go first: Travelx

**Comment by jalpa015** [comment]
My suggestions about making changes to the original README.md file are - 

  * We can make edits to the two of University Projects - 
image
  * We can push this message to the bottom of the project? If we are mentioning that we are accepting PRs it means that the project is still work in progress. 
image
  * About the title we can still keep it as Travelx.

**Comment by arun-esh** [comment]
> My suggestions about making changes to the original README.md file are - 
> 
> 
> 
>   * We can make edits to the two of University Projects - 
> 
> image
> 
>   * We can push this message to the bottom of the project? If we are mentioning that we are accepting PRs it means that the project is still work in progress. 
> 
> image
> 
>   * About the title we can still keep it as Travelx.
> 
> 

I think it will be easier to decide if we have PR 😂

**Comment by arun-esh** [comment]
> > My suggestions about making changes to the original README.md file are -
> > 
> > * We can make edits to the two of University Projects -
> > 
> > image
> > 
> > * We can push this message to the bottom of the project? If we are mentioning that we are accepting PRs it means that the project is still work in progress.
> > 
> > image
> > 
> > * About the title we can still keep it as Travelx.
> 
> I think it will be easier to decide if we have PR 😂

My bad, we should add our review so that @NIKHIL-techgeek can do the changes. The initial PR was raised by him.

**Review by arun-esh — CHANGES_REQUESTED** [review]

**Comment by arun-esh** [comment]
@jalpa015 I will change the name of the repo and url as well.

**Comment by jalpa015** [comment]
@arun-esh Thank you for the update.

@NIKHIL-techgeek  Could you kindly update the Readme with the new changes? Also please share your thoughts about the new ideas?

**Comment by NIKHIL-techgeek** [comment]
@jalpa015 , I was thinking that "How to Install" section should be in a separate file. Also , at the bottom the backend section doesn't make any sense. It looks like a placeholder. I will think of some content to add to the repo.

**Comment by jalpa015** [comment]
> @jalpa015 , I was thinking that "How to Install" section should be in a separate file. Also , at the bottom the backend section doesn't make any sense. It looks like a placeholder. I will think of some content to add to the repo.

@NIKHIL-techgeek, that sounds like a good idea to me. 

Do you think it is easy to create another PR for that? Maybe for now we can close this PR with the recommended changes and create a new Issue for your suggestion. I feel that way it is easy to manage and keep track. Let me know your thoughts :)

**Comment by NIKHIL-techgeek** [comment]
@jalpa015 Sure , We can create another PR for that. I too think that way things would be much easier for us.

**Comment by arun-esh** [comment]
@jalpa015 Please suggest what we can add:

- [ ] Pull requests are welcomed
- [ ] We need to write install procedures

**Review by arun-esh — CHANGES_REQUESTED** [review]
Instead of closing this PR, let's finish what was asked at the initial issue.

**Comment by jalpa015** [comment]
@arun-esh Please review changes

**Review by jalpa015 — APPROVED** [review]

**Review by arun-esh — APPROVED** [review]

**Pull request merged**
